# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160310_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[(b'cash', b'Cash')], default=b'cash', max_length=64, verbose_name='Payment method'),
        ),
    ]
